#!/usr/bin/env bash
# Show record type of domain & subdomain passed as arguments

domain_info (){
    rec=$(dig $1 $2 | awk 'f&&NR==f+1; /ANSWER SECTION:/ {f=NR}' | awk {'print $4'})
    ip=$(dig $2.$1 +short)
    echo "The subdomain $2 is a $rec record and points to $ip"
}

if [[ $# -eq 2 ]]; then
   domain_info "$1" "$2"
else
    for subdomain in www lb-01 web-01 web-02; do
	domain_info $1 $subdomain
    done
fi
