#!/usr/bin/env bash
# Show record type of domain & subdomain passed as arguments

domain_info (){
    rec=$(dig $1 $2 | awk 'f&&NR==f+1; /ANSWER SECTION:/ {f=NR}' | awk {'print $4'})
    ip=$(dig $2.$1 +short)
    echo "The subdomain $2 is a $rec record and points to $ip"
}

if [[ "$#" -eq 2 ]]; then
   domain_info $1 $2
else
   domain_info $1 www
   domain_info $1 lb-01
   domain_info $1 web-01
   domain_info $1 web-02
fi