#!/usr/bin/env bash
# configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo rm /var/www/html/index.nginx-debian.html
