#!/usr/bin/env bash
# configures a new Ubuntu machine
# configure web-02 to be identical to web-01
# configure Nginx so that its HTTP response contains a custom header

apt-get -y update
apt-get -y install nginx
service nginx start

#create hello world index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# redirect 301 for /redirect_me/
sed -i "/listen \[::\]:80 default_server;/a rewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# custom 404
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "/redirect_me/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html; internal;}" /etc/nginx/sites-available/default

# custom header
sed -i "/error_page/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart
