#!/usr/bin/env bash
# Create a file containing its PID, display an infinite loop "To infinity and beyond"
# Upon receiving a SIGTERM signal, display "I hate the kill command"
# Upon receiving a SIGINT signal, display "Y U no love me?!"
# Upon receiving a SIGQUIT OR SIGTERM signal, delete the created file and terminate itself
# touch /var/run/myscript.pid
clean_up()
{
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit
}

clean_up_int()
{
    echo "Y U no love me?!"
    exit
}

echo $BASHPID > /var/run/myscript.pid
trap clean_up_int SIGINT
trap clean_up SIGTERM SIGQUIT

while :
      do
	echo "To infinity and beyond"
	sleep 2
done
