#!/usr/bin/env bash
# Infinite loop to display "To infinity and beyond"
# Display "I am invincible!!!" when receiving a SIGTERM signal
trap 'echo I am invincible!!!' SIGTERM
while :
      do
	echo "To infinity and beyond"
	sleep 2
done
