#!/usr/bin/env bash
# Bash script displays numbers from 1 to 100, display FizzBuzz when multiple of
# 3 & 5, Fizz when multiple of 3 and Buzz when multiple of 5
for ((i = 1; i <= 100; i++))
    do
	if ((i % 3 == 0 && i % 5 == 0)); then
	   echo "FizzBuzz"
	elif ((i % 3 == 0)); then
	   echo "Fizz"
	elif ((i % 5 == 0)); then
	   echo "Buzz"
	else
	   echo "$i"
	fi
done