#!/usr/bin/env bash
# Bash script to display "Best School" 10 times, replacing line 4 & 8 with "bad luck"
i=1
while [ $i -lt 9 ]
      do
	if ((i == 4)) || ((i == 7)); then
	   echo "bad luck"
	fi
	echo "Best School"
	((i++))
done
