#!/usr/bin/env bash
# Bash script that displays 1 to 20, adding strings after line 4, 9, 17
i=1
while [ $i -le 20 ]
      do
	case $i in
	     	5)
		echo "bad luck from China"
		;;
		10)
		echo "bad luck from Japan"
		;;
		18)
		echo "bad luck from Italy"
		;;
	esac
	echo "$i"
	((i++))

done